spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crud_exercise_db
    username: root
    password: kadj0967
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false